# ONA Platform Automations for Magento 2.4.8 Development Environment
# Uses the correct ONA YAML format with services and tasks

# Services are long-running processes that should remain active
services:
  # Database service - handles MariaDB setup and startup
  database:
    name: MariaDB Database
    description: MariaDB database server for Magento 2
    triggeredBy:
      - postDevcontainerStart
    commands:
      start: |
        echo "Starting MariaDB service..."
        setup-mysql-data
        sudo service mariadb start
      ready: sudo service mariadb status
      stop: sudo service mariadb stop

  # Redis cache service
  redis:
    name: Redis Cache
    description: Redis cache server for Magento 2
    triggeredBy:
      - postDevcontainerStart
    commands:
      start: sudo service redis-server start
      ready: sudo service redis-server status
      stop: sudo service redis-server stop

  # PHP-FPM service
  php-fpm:
    name: PHP-FPM
    description: PHP FastCGI Process Manager
    triggeredBy:
      - postDevcontainerStart
    commands:
      start: sudo service php8.2-fpm start
      ready: sudo service php8.2-fpm status
      stop: sudo service php8.2-fpm stop

  # Nginx web server
  nginx:
    name: Nginx Web Server
    description: Nginx web server for Magento 2
    triggeredBy:
      - postDevcontainerStart
    commands:
      start: sudo service nginx start
      ready: sudo service nginx status
      stop: sudo service nginx stop

  # RabbitMQ message queue (optional, manual start)
  rabbitmq:
    name: RabbitMQ Message Queue
    description: RabbitMQ server for Magento 2 queues
    triggeredBy:
      - manual
    commands:
      start: rabbitmq-setup
      ready: sudo rabbitmqctl status
      stop: sudo service rabbitmq-server stop

# Tasks are one-time operations that run and complete
tasks:
  # Environment initialization task
  initialize-environment:
    name: Initialize Development Environment
    description: Setup and start all core Magento 2 services
    triggeredBy:
      - postDevcontainerStart
    command: |
      echo "Magento 2.4.8 Development Environment Ready!"
      echo "=============================================="
      versions
      echo ""
      echo "Next steps:"
      echo "1. Install Magento: ./m2-install.sh"
      echo "2. Check services: status-all"
      echo "3. Test database: test-db"
      echo ""
      echo "Web interface: Port 8002"
      echo "RabbitMQ Management: Port 15672 (start manually if needed)"

  # Manual task to start all services including RabbitMQ
  start-all-services:
    name: Start All Services
    description: Start all services including RabbitMQ
    triggeredBy:
      - manual
    command: magento-services start

  # Manual task to restart services
  restart-services:
    name: Restart All Services
    description: Restart all Magento 2 services
    triggeredBy:
      - manual
    command: restart-all

  # Manual database diagnostics
  database-diagnostics:
    name: Database Diagnostics
    description: Test and fix database connectivity issues
    triggeredBy:
      - manual
    command: |
      echo "Running database diagnostics..."
      test-db
      if ! test-db >/dev/null 2>&1; then
        echo "Attempting to fix database authentication..."
        fix-mysql
      fi
      echo "Database diagnostics complete!"

  # Development tools setup
  setup-dev-tools:
    name: Setup Development Tools
    description: Configure debugging and monitoring tools
    triggeredBy:
      - manual
    command: |
      echo "Development tools available:"
      echo "- xdebug-on/off     : Toggle Xdebug debugging"
      echo "- blackfire-config  : Setup Blackfire profiling" 
      echo "- newrelic-install  : Install New Relic monitoring"
      echo "- rabbitmq-config   : Configure RabbitMQ users"
      echo ""
      echo "Run any of these commands to configure tools as needed."

  # Magento installation helper
  install-magento:
    name: Install Magento 2.4.8-p2
    description: Install fresh Magento 2.4.8-p2 instance with all configurations
    triggeredBy:
      - manual
    command: |
      echo "Starting Magento 2.4.8-p2 installation..."
      echo "This will take several minutes..."
      
      # Ensure services are running
      if ! status-all | grep -q "MariaDB: Running"; then
        echo "Checking to make sure all required Magento 2 services are running..."
        magento-services start
        sleep 5
      fi
      
      # Run the installation script
      chmod +x /workspaces/magento2gitpod/m2-install.sh
      /workspaces/magento2gitpod/m2-install.sh
      
      echo "Magento installation completed!"
      echo "Check the output above for access URLs and credentials."
